Algoritmo "ProcedimentoExemplo"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/12/2024
Var
res, a1, n, r: inteiro
// Seção de Declarações das variáveis 
Procedimento TERMODAPA
var
aux: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
aux <- a1+(n-1)*r
res <- aux
fimprocedimento


inicio
a1 <- 20
n <- 8
r <- 4
TERMODAPA
escreva(res)

Fimalgoritmo